// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package scraperlang

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LeftBracket-0]
	_ = x[RightBracket-1]
	_ = x[LeftParen-2]
	_ = x[RightParen-3]
	_ = x[Comma-4]
	_ = x[Period-5]
	_ = x[Colon-6]
	_ = x[Tilde-7]
	_ = x[Equal-8]
	_ = x[SingleQuote-9]
	_ = x[DoubleQuote-10]
	_ = x[Ident-11]
	_ = x[Nil-12]
	_ = x[True-13]
	_ = x[False-14]
	_ = x[String-15]
	_ = x[Number-16]
	_ = x[Newline-17]
	_ = x[EOF-18]
}

const _TokenType_name = "LeftBracketRightBracketLeftParenRightParenCommaPeriodColonTildeEqualSingleQuoteDoubleQuoteIdentNilTrueFalseStringNumberNewlineEOF"

var _TokenType_index = [...]uint8{0, 11, 23, 32, 42, 47, 53, 58, 63, 68, 79, 90, 95, 98, 102, 107, 113, 119, 126, 129}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
