// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package scraperlang

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LeftBracket-0]
	_ = x[RightBracket-1]
	_ = x[LeftParen-2]
	_ = x[RightParen-3]
	_ = x[LeftCurlyBracket-4]
	_ = x[RightCurlyBracket-5]
	_ = x[Comma-6]
	_ = x[Period-7]
	_ = x[Colon-8]
	_ = x[Tilde-9]
	_ = x[Equal-10]
	_ = x[SingleQuote-11]
	_ = x[DoubleQuote-12]
	_ = x[Ident-13]
	_ = x[Tag-14]
	_ = x[Nil-15]
	_ = x[True-16]
	_ = x[False-17]
	_ = x[String-18]
	_ = x[Number-19]
	_ = x[Newline-20]
	_ = x[EOF-21]
}

const _TokenType_name = "LeftBracketRightBracketLeftParenRightParenLeftCurlyBracketRightCurlyBracketCommaPeriodColonTildeEqualSingleQuoteDoubleQuoteIdentTagNilTrueFalseStringNumberNewlineEOF"

var _TokenType_index = [...]uint8{0, 11, 23, 32, 42, 58, 75, 80, 86, 91, 96, 101, 112, 123, 128, 131, 134, 138, 143, 149, 155, 162, 165}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
